// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core_nucleus/local_first_db/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5409696372486298525),
      name: 'DeepDocument',
      lastPropertyId: const obx_int.IdUid(5, 3937742066658608803),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3110002736773246484),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7826164188169304997),
            name: 'globalKey',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 4434484662759143337)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2518533319901067263),
            name: 'collection',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 8551319676645104403)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1620206010971665092),
            name: 'payload',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3937742066658608803),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 5409696372486298525),
      lastIndexId: const obx_int.IdUid(2, 8551319676645104403),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DeepDocument: obx_int.EntityDefinition<DeepDocument>(
        model: _entities[0],
        toOneRelations: (DeepDocument object) => [],
        toManyRelations: (DeepDocument object) => {},
        getId: (DeepDocument object) => object.id,
        setId: (DeepDocument object, int id) {
          object.id = id;
        },
        objectToFB: (DeepDocument object, fb.Builder fbb) {
          final globalKeyOffset = fbb.writeString(object.globalKey);
          final collectionOffset = fbb.writeString(object.collection);
          final payloadOffset = fbb.writeString(object.payload);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, globalKeyOffset);
          fbb.addOffset(2, collectionOffset);
          fbb.addOffset(3, payloadOffset);
          fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final globalKeyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final collectionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final payloadParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final object = DeepDocument(
              id: idParam,
              globalKey: globalKeyParam,
              collection: collectionParam,
              payload: payloadParam,
              updatedAt: updatedAtParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DeepDocument] entity fields to define ObjectBox queries.
class DeepDocument_ {
  /// see [DeepDocument.id]
  static final id =
      obx.QueryIntegerProperty<DeepDocument>(_entities[0].properties[0]);

  /// see [DeepDocument.globalKey]
  static final globalKey =
      obx.QueryStringProperty<DeepDocument>(_entities[0].properties[1]);

  /// see [DeepDocument.collection]
  static final collection =
      obx.QueryStringProperty<DeepDocument>(_entities[0].properties[2]);

  /// see [DeepDocument.payload]
  static final payload =
      obx.QueryStringProperty<DeepDocument>(_entities[0].properties[3]);

  /// see [DeepDocument.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<DeepDocument>(_entities[0].properties[4]);
}
